//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class excelenciaEntities : DbContext
{
    public excelenciaEntities()
        : base("name=excelenciaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<acessos> acessos { get; set; }
    public DbSet<administradores> administradores { get; set; }
    public DbSet<agenda> agenda { get; set; }
    public DbSet<avaliacao> avaliacao { get; set; }
    public DbSet<cadastro> cadastro { get; set; }
    public DbSet<financiamento> financiamento { get; set; }
    public DbSet<historico_processo> historico_processo { get; set; }
    public DbSet<imobiliaria> imobiliaria { get; set; }
    public DbSet<processos> processos { get; set; }
    public DbSet<renda> renda { get; set; }
    public DbSet<representantes> representantes { get; set; }
    public DbSet<usuario> usuario { get; set; }
    public DbSet<vendedor> vendedor { get; set; }
}
