//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class acessos
{
    public int ID { get; set; }
    public Nullable<System.DateTime> Data { get; set; }
    public Nullable<int> Acessos1 { get; set; }
}

public partial class administradores
{
    public int Id { get; set; }
    public string usuario { get; set; }
    public string senha { get; set; }
    public int nivel { get; set; }
}

public partial class agenda
{
    public int Id { get; set; }
    public Nullable<System.DateTime> Data_Evento { get; set; }
    public string Titulo_Evento { get; set; }
    public string Descricao_Evento { get; set; }
    public Nullable<int> Usuario { get; set; }
    public Nullable<int> Status { get; set; }
}

public partial class avaliacao
{
    public int ID { get; set; }
    public Nullable<int> ID_Financiamento { get; set; }
    public Nullable<System.DateTime> Data_Solicitacao { get; set; }
    public Nullable<decimal> Valor { get; set; }
    public Nullable<System.DateTime> Data_Envio_Laudo { get; set; }
    public string Obs { get; set; }
}

public partial class cadastro
{
    public int ID { get; set; }
    public string Nome { get; set; }
    public string RG { get; set; }
    public string CPF { get; set; }
    public string Endereco { get; set; }
    public Nullable<System.DateTime> Data_Nascimento { get; set; }
    public string Estado_Civil { get; set; }
    public Nullable<int> Regime_Casamento { get; set; }
    public string Nome_Pai { get; set; }
    public string Nome_Mae { get; set; }
    public string Nome_Conjuge { get; set; }
    public string RG_Conjuge { get; set; }
    public string CPF_Conjuge { get; set; }
    public string Endereco_Conjuge { get; set; }
    public Nullable<System.DateTime> Data_Nascimento_Conjuge { get; set; }
    public string Nome_Pai_Conjuge { get; set; }
    public string Nome_Mae_Conjuge { get; set; }
    public Nullable<int> Imobiliaria { get; set; }
    public string Obs_Cliente { get; set; }
    public string Obs_Renda { get; set; }
    public string Senha { get; set; }
    public string Email { get; set; }
    public string Telefone_Fixo { get; set; }
    public string Telefone_Comercial { get; set; }
    public string Telefone_Celular { get; set; }
    public Nullable<System.DateTime> Data_Cadastro { get; set; }
    public Nullable<int> Usuario_Responsavel { get; set; }
    public Nullable<System.DateTime> Data_Alteracao { get; set; }
    public Nullable<int> Usuario_Alteracao { get; set; }
    public Nullable<System.DateTime> Ultimo_Acesso { get; set; }
    public Nullable<int> Status { get; set; }

    public virtual imobiliaria imobiliaria1 { get; set; }
}

public partial class financiamento
{
    public int ID { get; set; }
    public Nullable<int> ID_Cliente { get; set; }
    public Nullable<int> ID_Processo { get; set; }
    public Nullable<decimal> Valor_Imovel { get; set; }
    public Nullable<decimal> Entrada { get; set; }
    public Nullable<decimal> Valor_Financiamento { get; set; }
    public string FGTS { get; set; }
    public string Subsidio { get; set; }
    public string Prazo { get; set; }
    public string Tabela { get; set; }
    public string Modalidade { get; set; }
    public string Endereco { get; set; }
    public string Cidade { get; set; }
    public Nullable<short> Condicao { get; set; }
    public string Matricula { get; set; }
    public string IPTU { get; set; }
    public string Obs_Financiamento { get; set; }
    public string Obs_Imovel { get; set; }
    public Nullable<System.DateTime> Data_Cadastro { get; set; }
    public Nullable<int> Usuario_Responsavel { get; set; }
    public Nullable<System.DateTime> Data_Alteracao { get; set; }
    public Nullable<int> Usuario_Alteracao { get; set; }
}

public partial class historico_processo
{
    public int ID { get; set; }
    public string Processo { get; set; }
    public Nullable<int> ID_Processo { get; set; }
    public Nullable<int> ID_Cliente { get; set; }
    public string Evento { get; set; }
    public Nullable<System.DateTime> Data_Evento { get; set; }
    public Nullable<int> Usuario_Responsavel { get; set; }
}

public partial class imobiliaria
{
    public imobiliaria()
    {
        this.cadastro = new HashSet<cadastro>();
    }

    public int ID { get; set; }
    public string Nome { get; set; }
    public string Identificador { get; set; }
    public string Senha { get; set; }
    public string Email { get; set; }
    public Nullable<System.DateTime> Ultimo_Acesso { get; set; }
    public Nullable<int> Status { get; set; }

    public virtual ICollection<cadastro> cadastro { get; set; }
}

public partial class processos
{
    public int ID { get; set; }
    public Nullable<int> ID_Cliente { get; set; }
    public Nullable<System.DateTime> Data_Cadastro { get; set; }
    public Nullable<int> Responsavel { get; set; }
}

public partial class renda
{
    public int ID { get; set; }
    public Nullable<int> ID_Cliente { get; set; }
    public Nullable<int> Tipo_Renda { get; set; }
    public Nullable<int> Controle { get; set; }
    public string Profissao { get; set; }
    public string Ramo_Atividade { get; set; }
    public string Empresa { get; set; }
    public Nullable<decimal> Renda1 { get; set; }
    public string Tempo_Servico { get; set; }
}

public partial class representantes
{
    public int Id { get; set; }
    public string nome { get; set; }
    public string usuario { get; set; }
    public string senha { get; set; }
    public string email { get; set; }
    public string regiao { get; set; }
    public string telefone { get; set; }
    public string telefone2 { get; set; }
    public string estado { get; set; }
    public string obs { get; set; }
}

public partial class usuario
{
    public int ID { get; set; }
    public string Nome { get; set; }
    public string CPF { get; set; }
    public string Senha { get; set; }
    public string Perfil { get; set; }
    public Nullable<System.DateTime> Ultimo_Acesso { get; set; }
    public Nullable<int> Status { get; set; }
}

public partial class vendedor
{
    public int ID { get; set; }
    public Nullable<int> ID_Cliente { get; set; }
    public string Sessao { get; set; }
    public string Nome { get; set; }
    public string RG { get; set; }
    public string CPF { get; set; }
    public string Endereco { get; set; }
    public Nullable<System.DateTime> Data_Nascimento { get; set; }
    public string Email { get; set; }
    public string Telefone_Fixo { get; set; }
    public string Telefone_Comercial { get; set; }
    public string Telefone_Celular { get; set; }
    public string Estado_Civil { get; set; }
    public string Nome_Pai { get; set; }
    public string Nome_Mae { get; set; }
    public string Nome_Conjuge { get; set; }
    public string RG_Conjuge { get; set; }
    public string CPF_Conjuge { get; set; }
    public string Endereco_Conjuge { get; set; }
    public Nullable<System.DateTime> Data_Nascimento_Conjuge { get; set; }
    public string Nome_Pai_Conjuge { get; set; }
    public string Nome_Mae_Conjuge { get; set; }
    public string Obs { get; set; }
    public Nullable<System.DateTime> Data_Cadastro { get; set; }
    public Nullable<int> Usuario_Cadastro { get; set; }
}
